<a href="https://colab.research.google.com/github/gowriv05/Numpy_Pandas/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy and Pandas Data Analysis Assignment
## Objective
This assignment focuses on performing data analysis using NumPy and Pandas.

The main objectives are:
- Working with NumPy arrays for numerical computations
- Creating and manipulating Pandas Series
- Creating and analyzing Pandas DataFrames
- Applying indexing, slicing, filtering, and aggregation
- Performing data manipulation using Python

## 1. Create a 1D NumPy Array

A 1D NumPy array named `temperatures_w1` is created to store the daily average temperatures for Week 1.

In [1]:
import numpy as np
temperatures_w1=np.array([22.5,23.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 23.3 20.8 23.4 26.1 24.8 21.9]


## 2. Inspection and Properties

The shape, data type, and number of elements in the Week 1 temperature array are inspected using NumPy properties.

In [2]:
print("Shape:",temperatures_w1.shape)
print("Data type:",temperatures_w1.dtype)
print("Number of elements:",temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7


## 3. Convert Celsius to Fahrenheit

The temperatures are converted from Celsius to Fahrenheit using the formula:
Fahrenheit = (Celsius × 9/5) + 32

In [3]:
temperatures_f=(temperatures_w1*9/5)+32
print(temperatures_f)

[72.5  73.94 69.44 74.12 78.98 76.64 71.42]


### Maximum, Minimum and Mean Temperature

In [4]:
print("Maximum temperature:",temperatures_w1.max())
print("Minimum temperature:",temperatures_w1.min())
print("Mean temperature:",temperatures_w1.mean())

Maximum temperature: 26.1
Minimum temperature: 20.8
Mean temperature: 23.25714285714286


## 4. Array Slicing and Indexing

Array slicing is used to extract temperatures for specific days of the week.

In [5]:
first_three_days=temperatures_w1[:3]
print("First 3 days:",first_three_days)
week_end=temperatures_w1[-2:]
print("Week end:",week_end)
middle_three_days=temperatures_w1[2:5]
print("Middle 3 days:",middle_three_days)


First 3 days: [22.5 23.3 20.8]
Week end: [24.8 21.9]
Middle 3 days: [20.8 23.4 26.1]


## 5. Create a 2D NumPy Array

A 2D NumPy array named `temperatures` is created.

Each row represents the temperatures recorded during a different week.

In [6]:
temperatures=np.array([
    [22.5,23.3,20.8,23.4,6.1,24.8,21.9],
    [19.2,22.5,21.3,24.0,23.5,22.8,20.1]
])
print(temperatures)

[[22.5 23.3 20.8 23.4  6.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


## 6 Inspect and Slice the 2D Array

Inspect the shape, data type, and total number of elements in the 2D array.

Extract:
- Week 1 temperatures
- Week 2 temperatures
- Weekend temperatures for both weeks

In [7]:
print("Shape:",temperatures.shape)
print("Data type:",temperatures.dtype)
print("Number of elements:",temperatures.size)

Shape: (2, 7)
Data type: float64
Number of elements: 14


In [8]:
week_1=temperatures[0]
week_2=temperatures[1]
print("Week 1",week_1)
print("Week 2",week_2)

Week 1 [22.5 23.3 20.8 23.4  6.1 24.8 21.9]
Week 2 [19.2 22.5 21.3 24.  23.5 22.8 20.1]


In [9]:
weekend_both_weeks=temperatures[:,-2:]
print("Weekend temperatures for both weeks:\n",weekend_both_weeks)

Weekend temperatures for both weeks:
 [[24.8 21.9]
 [22.8 20.1]]


# Pandas Series

A Pandas Series is a one-dimensional labeled data structure.

## 1. Creating a Pandas Series

A Pandas Series named `marks` is created with custom index labels representing student ranks.

In [10]:
import pandas as pd
marks=pd.Series([95,92,89,85,80],index=['Rank1','Rank2','Rank3','Rank4','Rank5'])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


## 2.2 Indexing and Slicing

Perform the following operations:

- Access the mark of the 1st rank student using integer position
- Retrieve the top 3 ranks using `loc`
- Retrieve the 3rd-ranked student's mark using `iloc`
- Filter students whose marks are greater than 90

In [11]:
# Mark of first rank student
print("Marks of first rank student",marks.iloc[0])

# Top 3 ranks
print("\nTop 3 ranks\n",marks.loc[['Rank1','Rank2','Rank3']])

# 3rd rank student
print("\nMark of third rank student:",marks.iloc[2])

# Marks greater than 90
print("\nMarks greater than 90\n",marks[marks>90])


Marks of first rank student 95

Top 3 ranks
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

Mark of third rank student: 89

Marks greater than 90
 Rank1    95
Rank2    92
dtype: int64


## 2.3 Manipulating the Series

Perform the following operations:

- Modify the 1st rank student's mark to 100
- Remove the entry corresponding to Rank5
- Calculate CGPA by dividing each mark by 10

In [12]:
# Modify 1st rank mark
marks.loc['Rank1']=100
print(marks)

# Remove last rank
marks=marks.drop('Rank5')
print("\nAfter removing the last rank:\n",marks)

# CGPA
cgpa=marks/10
print("\nCGPA:\n",cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing the last rank:
 Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# 3. Pandas DataFrame

In this section, a transaction dataset is created and explored using Pandas DataFrame operations.

## 3.1 Create the Transactions DataFrame

Create a DataFrame named `transactions` containing TransactionID, ProductCategory, Region, and Amount.

In [13]:
transactions = pd.DataFrame({
    'TransactionID':[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory':['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
                       'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region':['North', 'South', 'North', 'East', 'West',
              'North', 'East', 'West', 'South', 'North'],
    'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
transactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


## 3.2 Data Exploration

Explore the transactions DataFrame using:

- `head()`
- `tail()`
- `shape`
- `columns`
- `dtypes`

In [14]:
print("First 5 rows:\n",transactions.head())
print("\nLast 5 rows:\n",transactions.tail())
print("\nShape:\n",transactions.shape)
print("\nColumns:\n",transactions.columns)
print("\nDatatypess:\n",transactions.dtypes)

First 5 rows:
    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:
    TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape:
 (10, 4)

Columns:
 Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

Datatypess:
 TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object


## 3.3 Select Specific Columns

Display only the `ProductCategory` and `Amount` columns.

## 3.4 Retrieve the Last Three Columns

Use `iloc` or `loc` to retrieve the last three columns of the DataFrame.

In [15]:
print(transactions[['ProductCategory','Amount']])

# Last 3 columns
print("\nLast 3 columns:\n")
print(transactions.iloc[:,-3:])

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

Last 3 columns:

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


## 3.5 Filter Transactions

Filter the transactions where:

- Region is `North`
- Amount is greater than 200

In [16]:
filtered_transactions=transactions[(transactions['Region']=='North') & (transactions['Amount']>200)]
print(filtered_transactions)

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


## 3.6 Analyze Product Categories

Find the number of transactions for each `ProductCategory` using `value_counts()`.

In [17]:
print(transactions['ProductCategory'].value_counts())

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


## 3.7 Find Unique Regions

Find the unique values present in the `Region` column.

In [18]:
print(transactions['Region'].unique())

['North' 'South' 'East' 'West']


## 3.8 Group Transactions by Region

Group the transactions by `Region` and calculate the mean `Amount` for each region.

In [25]:
mean_regions=transactions.groupby('Region')['Amount'].mean()
print(mean_regions)

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


# 4. DataFrame Manipulation

In this section, the transactions DataFrame is modified by updating values, adding columns, and removing rows and columns.

## 4.1 Modify Transaction Amount

Modify the Amount for TransactionID 102 from 150 to 165.

In [26]:
transactions.loc[transactions['TransactionID']==102,'Amount']=165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


## 4.2 Add a Discount Column

Add a new column named `Discount` by calculating 10% of the transaction Amount.

In [27]:
transactions['Discount']=transactions['Amount']*0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0


## 4.3 Remove TransactionID 109

Remove the row corresponding to TransactionID 109 from the DataFrame.

In [31]:
transactions=transactions.drop(transactions[transactions['TransactionID']==109].index)
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


## 4.4 Delete the Discount Column

Delete the `Discount` column from the DataFrame.

In [28]:
transactions=transactions.drop(columns=['Discount'])
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


# 5. Final Result

The NumPy and Pandas operations were successfully performed, including:

- NumPy array creation and manipulation
- Array indexing and slicing
- Temperature conversion and aggregation
- Pandas Series creation and indexing
- Boolean filtering
- Series manipulation
- DataFrame creation and exploration
- Conditional filtering
- Grouping and aggregation
- DataFrame modification
- Adding and deleting rows and columns